apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-secure
  namespace: node-app-secure
  labels:
    app: node-app-secure
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-app-secure
  template:
    metadata:
      labels:
        app: node-app-secure
    spec:
      containers:
        - name: node-app-secure
          image: wincor411/node-app-secure:latest
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "200m"
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 15
